// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class Cliente
{
    public int Id { get; set; }

    public string NumeroIdentificacion { get; set; }

    public string NombreCliente { get; set; }

    public string Telefono { get; set; }

    public virtual ICollection<DetalleLih> DetalleLih { get; set; } = new List<DetalleLih>();

    public virtual ICollection<DetalleVendido> DetalleVendido { get; set; } = new List<DetalleVendido>();
}