// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class Perfil
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<PerfilPermisos> PerfilPermisos { get; set; } = new List<PerfilPermisos>();

    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}