// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class Producto
{
    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public int IdDepartamento { get; set; }

    public int IdCategoria { get; set; }

    public int IdLineaServicio { get; set; }

    public int IdSubLineaServicio { get; set; }

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual Departamento IdDepartamentoNavigation { get; set; }

    public virtual LineaServicio IdLineaServicioNavigation { get; set; }

    public virtual SubLineaServicio IdSubLineaServicioNavigation { get; set; }

    public virtual ICollection<ItemInventario> ItemInventario { get; set; } = new List<ItemInventario>();
}