// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class Usuario
{
    public int Id { get; set; }

    public string NombreUsuario { get; set; }

    public string Contrasena { get; set; }

    public int IdPerfil { get; set; }

    public virtual ICollection<Empleado> Empleado { get; set; } = new List<Empleado>();

    public virtual Perfil IdPerfilNavigation { get; set; }
}