// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class DetalleNoOperativo
{
    public int Id { get; set; }

    public int IdItemNoOp { get; set; }

    public DateTime Fecha { get; set; }

    public string Justificativo { get; set; }

    public bool AprobarBajaInventario { get; set; }

    public string EspecificarOtro { get; set; }

    public int IdEstatusNoOp { get; set; }

    public virtual Estatus IdEstatusNoOpNavigation { get; set; }

    public virtual ItemsNoOperativo IdItemNoOpNavigation { get; set; }
}