// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class DetalleLih
{
    public int Id { get; set; }

    public int IdEstatusLih { get; set; }

    public DateTime Fecha { get; set; }

    public int IdCliente { get; set; }

    public string Pozo { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Estatus IdEstatusLihNavigation { get; set; }
}