// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class Estatus
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<DetalleLih> DetalleLih { get; set; } = new List<DetalleLih>();

    public virtual ICollection<DetalleNoOperativo> DetalleNoOperativo { get; set; } = new List<DetalleNoOperativo>();

    public virtual ICollection<DetalleVendido> DetalleVendido { get; set; } = new List<DetalleVendido>();

    public virtual ICollection<TransaccionesEstadoItem> TransaccionesEstadoItem { get; set; } = new List<TransaccionesEstadoItem>();
}