// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class FormaRegistro
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<InformacionRegistro> InformacionRegistro { get; set; } = new List<InformacionRegistro>();
}