// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class ItemInventario
{
    public int Id { get; set; }

    /// <summary>
    /// Código propio identificador para el usuario.
    /// </summary>
    public string CodigoItem { get; set; }

    public string Departamento { get; set; }

    public string Categoria { get; set; }

    public string LineaServicio { get; set; }

    public string SubLineaServicio { get; set; }

    public string DescripcionEspecifica { get; set; }

    public string EspecificacionesTecnicas { get; set; }

    public DateTime FechaCompra { get; set; }

    public decimal ValorSinIva { get; set; }

    public string NumeroParteFabricante { get; set; }

    public string NumeroSerieLps { get; set; }

    public string Estatus { get; set; }

    public int IdUbicacion { get; set; }

    public int IdClasificacion { get; set; }

    /// <summary>
    /// Clave foránea que ya tiene detalles
    /// </summary>
    public string CodigoProducto { get; set; }

    public int IdProveedor { get; set; }

    public int IdInformacionRegistro { get; set; }

    public virtual Producto CodigoProductoNavigation { get; set; }

    public virtual Clasificacion IdClasificacionNavigation { get; set; }

    public virtual InformacionRegistro IdInformacionRegistroNavigation { get; set; }

    public virtual Proveedor IdProveedorNavigation { get; set; }

    public virtual Ubicacion IdUbicacionNavigation { get; set; }

    public virtual ICollection<NovedadItem> NovedadItem { get; set; } = new List<NovedadItem>();

    public virtual ICollection<TransaccionesEstadoItem> TransaccionesEstadoItem { get; set; } = new List<TransaccionesEstadoItem>();
}