// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class LineaServicio
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Producto> Producto { get; set; } = new List<Producto>();

    public virtual ICollection<SubLineaServicio> SubLineaServicio { get; set; } = new List<SubLineaServicio>();
}