// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventarioLPS.Data.Entities;

public partial class Proveedor
{
    public int Id { get; set; }

    public string Ruc { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string Direccion { get; set; }

    public string PersonaContacto { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public virtual ICollection<CorreoAdicionalProveedor> CorreoAdicionalProveedor { get; set; } = new List<CorreoAdicionalProveedor>();
}