// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using InventarioLPS.Data.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace InventarioLPS.Data
{
    public partial class InventarioLPSContext
    {
        private IInventarioLPSContextProcedures _procedures;

        public virtual IInventarioLPSContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new InventarioLPSContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IInventarioLPSContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class InventarioLPSContextProcedures : IInventarioLPSContextProcedures
    {
        private readonly InventarioLPSContext _context;

        public InventarioLPSContextProcedures(InventarioLPSContext context)
        {
            _context = context;
        }
    }
}
